### ISSUE TITLE
python demo_synthetic.py giving unexpected keyword argument 'warm_start' Error

### ISSUE THREAD

**Issue by devanandR** [kelicht/ordce#1]
Hi,
I am getting the following error message when I am hitting the "python demo_synthetic.py" command. 
I think I have installed all the required packages

# 1-th Denied Individual:
        - x_1: Education       : 1.0
        - x_2: JobSkill        : 1.0
        - x_3: Income          : 29.0
        - x_4: WorkPerDay      : 6.0
        - x_5: HealthStatus    : 6.0
## TLPS (non-order):
Traceback (most recent call last):
  File "demo_synthetic.py", line 92, in <module>
    demonstration(clf='lr', n=1, costs=['TLPS'])
  File "demo_synthetic.py", line 78, in demonstration
    oa = oce.extract(x, K=5, ordering=False, post_ordering=False, cost_type=cost)
  File "C:\Users\1021399\Documents\AshuTusharDev\CE\ordce-main\ordce-main\linear_oce.py", line 212, in extract
    prob.solve(solver=pulp.CPLEX_PY(msg=log_stream, warm_start=(len(init_sols)!=0), timeLimit=time_limit, options=['set output clonelog -1']))
TypeError: __init__() got an unexpected keyword argument 'warm_start'
I am running it on the windows box. 

I remember running the same on Linux box was giving me "raise PulpSolverError(CPLEX_PY: Not Available)". I would like to ask that do we require a separate cplex installation in my Linux box?

What is wrong with my side? 
Thank you in advance.

Regards,
Devanand

**Comment by devanandR** [comment]
I forgot to add that the windows box has 12.10 version of cplex.

Regards,
Devanand

**Comment by devanandR** [comment]
The problem was with pulp and path of CPLEX I am using. Temporarily, I set it manually in the code - I just added path_to_cplex  before solving the milp , I called pulp.CPLEX_CMD(path_to_cplex). It worked. 

Thanks, I am closing it.

Regards,
Dev
